### ISSUE TITLE
第一个例子就报错！

### ISSUE THREAD

**Issue by yazhoushi** [gateio/gatews#1]
asyncio.create_task(self._write(conn), name='write')
asyncio.create_task这个函数官方asyncio库不能带参数吧！我python3.7.1

**Comment by yazhoushi** [comment]
def create_task(coro):
    """Schedule the execution of a coroutine object in a spawn task.

    Return a Task object.
    """
    loop = events.get_running_loop()
    return loop.create_task(coro)
官方函数

**Comment by revilwang** [comment]
name参数是在3.8以后引入的，这里的确是版本兼容问题，稍候修复

**Comment by revilwang** [comment]
推送了 0.1.1 更新，修复 Python 3.8 以下版本兼容性问题，`pip install --upgrade gate-ws` 升级到最新版

**Comment by revilwang** [comment]
无响应，本 issue 关闭
