### ISSUE TITLE
subscribe all user data events in one ws connection

### ISSUE THREAD

**Issue by ioogle** [gateio/gatews#11]
Thanks for your hard work! But there are two critical problems that I found in your futures API:

### 1. Some connections are contract specific which is inconvenient

For example, for [User Trades API](https://www.gate.io/docs/futures/ws/index.html#usertrades-api), the connection is contract specific:

```
from websocket import create_connection
ws = create_connection("wss://fx-ws-testnet.gateio.ws/v4/ws/btc")
ws.send('{
    "time" : 123456,
    "channel" : "futures.usertrades",
    "event": "subscribe",
    "payload" : ["20011", "BTC_USD"],
    "auth": {
            "method": "api_key",
            "KEY":"xxxx",
            "SIGN": "xxxx"
            }}')
print(ws.recv())
```

which means that `N` connections are needed if we want to receive notifications from `N` contracts.

### 2. If all user-specific data can be integrated with one connection, it will be much better

As far as I know, Binance provides a single Websocket endpoint [User Data Stream](https://binance-docs.github.io/apidocs/futures/en/#user-data-streams) to receive all user updates, and that's really awesome.

**Comment by revilwang** [comment]
Actually there are examples that you can subscribe to multiple channels with multiple contracts using one connection

**Comment by revilwang** [comment]
For example

```python
from gate_ws import Configuration, Connection
from gate_ws.futures import FuturesUserTradesChannel, FuturesBalanceChannel


async def main():
    conn = Connection(Configuration(api_key='YOUR_API_KEY',
                                    api_secret='YOUR_API_SECRET', 
                                    default_callback=lambda c, r: print(r.result),
                                    app='futures', settle='usdt')
    balance_channel = FuturesBalanceChannel(conn)
    balance_channel.subscribe(["BTC_USDT", "ETH_USDT"])

    user_trade_channel = FuturesUserTradesChannel(conn)
    user_trade_channel.subscribe(["YOUR_USER_ID", "BTC_USDT"])
    user_trade_channel.subscribe(["YOUR_USER_ID", "ETH_USDT"])

    # start the client
    await conn.run()

```

**Comment by ioogle** [comment]
Thanks. But considering that there are around 7-8 user-specific endpoints that are also contract specific. If I want to monitor all of the contracts, there might be hundreds of connections which may be unacceptable.

**Comment by revilwang** [comment]
The example above use only one connection to subscribe to multiple channels with multiple contracts. Even for contract specific channels, you can call subscribe multiples times with different contracts. You can receive all subscription's updates in one connection.

**Comment by ioogle** [comment]
That's really cool. Would you mind providing an example for Golang?

**Comment by revilwang** [comment]
The [example in quick start](https://github.com/gateio/gatews/tree/master/go#readme) shows how to do so

**Comment by ioogle** [comment]
Thank you again for your patient reply:)
