### ISSUE TITLE
请问spot.order_book通道最多可以订阅多少个交易对？

### ISSUE THREAD

**Issue by kelaile** [gateio/gatews#15]
您好！请问spot.order_book通道最多可以订阅多少个交易对？有限制么？目前使用的是golang

**Comment by revilwang** [comment]
没有上限

**Comment by fangchain** [comment]
请问订阅的交易对太多是不是有数据推送延迟？我这里测试订阅几十个交易对就会有延迟，延迟几秒几十秒的都有

**Comment by revilwang** [comment]
没有上限的约束，但是深度本身推送频率高，很容易造成发送队列阻塞，甚至因为客户端队列满被服务端强制关闭
