### ISSUE TITLE
Problem subscribing FuturesUserTradesChannel

### ISSUE THREAD

**Issue by MaoXuYin** [gateio/gatews#16]
Cant find my mistake, any ideas why the status is failed?

I want to get notified if an order got filled.

Edit: Nevermind, got it. I dont know why, but we need the UserID.

![image](https://user-images.githubusercontent.com/40123505/143536935-5d8f7e4e-7cce-45f5-a3dc-6eab206891dc.png)

**Comment by revilwang** [comment]
You can view corresponding WebSocket documents, which says `futures.usertrades` requires a string user ID in front. Try to change `channel.subscribe(['BTC_USDT'])` to `channel.subscribe(['<YOUR_USER_ID>', 'BTC_USDT'])`.
