### ISSUE TITLE
Delivery Futures - No mapping possible due to missing information in response

### ISSUE THREAD

**Issue by ChristianCoenen** [gateio/gatews#18]
Currently, only the WebSocket servers for ```Spot``` and ```Perpetual Futures``` return an ID when subscribing to a channel (as stated in the gateio documentation).
<img width="648" alt="Screenshot 2021-12-12 at 11 44 19" src="https://user-images.githubusercontent.com/22744609/145709265-ab583517-c14f-4a01-b106-8344937cdb87.png">

However, the ```Delivery Futures``` WebSocket server does not send back an ID or the payload in the subscribe response => no mapping possible. This makes it impossible to properly create automated trading tools for the delivery futures on gateio!

Analyzing the code, it looks to me that currently an old implementation is used for the ```Delivery Futures```. Is it planned to be migrated into this codebase in the near future? If not, I would recommend a small update to add the request-id to the response for subscribe and unsubscribe events. 

Please let me know if I should open the issue in the [old repository](https://github.com/gateio/WebSocket-API/issues) as well.

**Comment by revilwang** [comment]
Yes, the delivery futures currently does not send back the ID in request payload. We'll add this feature, when it's finished, I'll report here.

**Comment by revilwang** [comment]
Feature has been supported (though really a bit late)
