### ISSUE TITLE
Go mod tag version

### ISSUE THREAD

**Issue by LogansUA** [gateio/gatews#19]
Hey,
I'm trying to lock the version in `go.mod` to `github.com/gateio/gatews v0.2.4` (v0.2.4 is the latest release tag). But it seems that because an actual Golang code is in `github.com/gateio/gatews/go` directory and in project it's used as
```go
import gate "github.com/gateio/gatews/go"
```
the `go.mod` is locking it to the latest commit hash `github.com/gateio/gatews/go v0.0.0-20211015033957-f7c469464a59`.

It's not somehow affecting our flow, just wanted to maintain a proper versions of modules.

Do you know how can I change this? Or maybe you could publish a better tag distinction?

Regards,
Thanks

**Comment by revilwang** [comment]
Upgrade the version to v0.2.5. v0.2.4 tag has been falsely broken before.
