### ISSUE TITLE
请问如何计算永续合约全仓仓位占用并锁定的保证金？

### ISSUE THREAD

**Issue by newlju** [gateio/gatews#20]
如何计算永续合约全仓仓位占用并锁定的保证金？就是在web仓位页面“保证金”那一栏，保证金会随着价格变化而增减，我想计算某个价格时需要多少保证金怎么计算？

**Comment by revilwang** [comment]
如果浮盈：初始保证金
如果浮亏：初始保证金+abs(浮亏)
