### ISSUE TITLE
请问如何下数量有小数点如0.001这样的合约单子？

### ISSUE THREAD

**Issue by zenchanhk** [gateio/gatews#23]
FuturesOrder的size 是long，没法下小于1的单子。但是app和web都可以下，请问API改如何设置？谢谢

**Comment by revilwang** [comment]
size 是合约张数，张数和币的转换关系是 Contract 里的 `quanto_multiplier` ，app 和 web 下单只是把合约张数转换成了币的数量，实际下单还是会转换成合约张数

**Comment by zenchanhk** [comment]
哦哦，明白了，谢谢
