### ISSUE TITLE
Can anyone help me about placing spot order?

### ISSUE THREAD

**Issue by ikaraburc** [gateio/gatews#26]
I am new, I want to learn how to place an order with python websocket app in gate.io.. thanks to all

**Comment by revilwang** [comment]
You need to use [gate-api](https://github.com/gateio/gateapi-python) to place order. gatews doesn't support it.

`pip install gate-api`

**Comment by ikaraburc** [comment]
Dear revilwang thank you for your kind help. it may be a silly question, if we can not place an order by using gateway what is the use of gatews and how can get benefit from it? Thank you in advance

**Comment by revilwang** [comment]
You can trade without gatews at all. However  gatews can help you get recent market data faster. Another thing is gatews pushes new update to you, while using gate-api, you need to query periodically yourself

**Comment by ikaraburc** [comment]
I have my own python code for gateio coins trade written by me by using restapi. But I want to get data by websocket to get the data faster  and change my buy/sell orders as per websocket data. Is this possible? if not possible, only to getting by websocket should be useless?

**Comment by revilwang** [comment]
Of course it is possible. I suggest you can try the gatews examples to have a quick impression about what gatews can do for you. For detailed data websocket provides, refer to the official WebSocket reference [documents](https://www.gate.io/docs/developers/apiv4/ws/en/)
