### ISSUE TITLE
i have issue with the trade order not being visible in the API( "GET /spot/my_trades" endpoint.)

### ISSUE THREAD

**Issue by gyeonghankim** [gateio/gatews#27]
Hello.
As you see on the attached file below, on the "https://www.gate.io/myaccount/mypurselog" page, you can find "Quick Buy-Bought" and "Quick Sell-Sold" data as the action type. (refer to the screenshot, red squared data)
We assume the data (*red squared data) as the "trade" data.
That's why we predicted the data to search through the "GET /spot/ my_trades" endpoint. But it did not work.
The question is, "searching data, do we need to use different end points? Or is it simply the system error?"

![Screen Shot 2022-03-10 at 4 16 02 PM](https://user-images.githubusercontent.com/96705688/157799982-e707f5e2-7b6e-4a93-a7b1-f7129ace216f.png)

**Comment by revilwang** [comment]
`/spot/my_trades` only returns trades with spot only. Quick Buy/Sell is not related to spot trading, and it is not available through API.
