### ISSUE TITLE
Hi can you provide simple example to listen uer trade on spot using websocket,i already try but the server didnt receive any response when the order is finished

### ISSUE THREAD

**Issue by Ivanrputra** [gateio/gatews#29]

**Comment by Ivanrputra** [comment]
![image](https://user-images.githubusercontent.com/8486138/161367563-8233038f-7d6b-4944-951c-e350a03d31c0.png)

This is my code to listen price and trade order

**Comment by revilwang** [comment]
The code seems fine to me. Do you print the error message and find any error message on subscription?

**Comment by Ivanrputra** [comment]
> The code seems fine to me. Do you print the error message and find any error message on subscription?

No error message, but what is the different between spot.order and spot.usertrade ?

**Comment by revilwang** [comment]
`spot.order` pushes every order update, while `spot.usertrade` pushes trades update. If order has no fill, then no update will be received from `spot.usertrade`

**Comment by Ivanrputra** [comment]
one

> `spot.order` pushes every order update, while `spot.usertrade` pushes trades update. If order has no fill, then no update will be received from `spot.usertrade`

thank you for the explanation, 
i got one last question, when i want to know if my buy or sell order is close or fully filled which websocket should i use?

**Comment by revilwang** [comment]
`spot.order`. It pushes every order update and when the order is cancelled or finished, the `event` field in the order object(not the outmost `event`) will be updated to `finish`. And  you can check if `left` is `"0"` to make sure if the order is fully filled.

**Comment by Ivanrputra** [comment]
> `spot.order`. It pushes every order update and when the order is cancelled or finished, the `event` field in the order object(not the outmost `event`) will be updated to `finish`. And you can check if `left` is `"0"` to make sure if the order is fully filled.

ok thank you very much, 
i will close the issue
