### ISSUE TITLE
订阅永续Private channel， 每一分钟就被服务器断开连接

### ISSUE THREAD

**Issue by dhw970805** [gateio/gatews#32]
现货不会出现，永续稳定出现，关闭原因： The remote party closed the WebSocket connection without completing the close handshake， 有持续发ping pong，两个账号中一个稳定出现这个问题，另一个不出现

**Comment by revilwang** [comment]
永续合约是订阅的哪种结算

**Comment by revilwang** [comment]
与 #34 issue 应该是一个问题，可以升级到最新版本验证一下
