### ISSUE TITLE
Your order size 1 is too small. The minimum is 1 USDT

### ISSUE THREAD

**Issue by negocio-azul** [gateio/gatews#33]
Hello guys,

I'm trying send GOLD_USDT orders through de API V.4, but some errors have been happening.

If I send a order with amount=2 and price=0.009321, I receive the error message:
_'Your order size 2 is too small. The minimum is 1 USDT'_
The message don't make sense. Is 2 less than 1?

The data/body is:
{
"text":"",
"currency_pair":"GOLD_USDT",
"type":"limit",
"account":"spot",
"side":"buy",
**"amount":"2"**,
"price":"0.0093210",
"time_in_force":"gtc"
}

But, if I send an order with amount=2 and price **1**.009321, this works fine. (Price > 1).
This was only to test, because the price 1.009321 is very expensive.

So, I don't understand what's happening. 
Probably, the validation is inverted in the API.

Could someone help me?

Thanks.

**Comment by revilwang** [comment]
The value of your order amount must be more than 1U. Note the currency unit in error message
