### ISSUE TITLE
Best bid/ask timestamp semantics

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#36]
Hello there,

I have a question regarding best bid/ask notifications coming from WebSocket API (https://www.gate.io/docs/developers/futures/ws/en/#best-ask-bid-notification). There's a timestamp provided in the notification - "t", comment says it's "Book ticker generated timestamp in milliseconds". Does this timestamp represent the time when the change occurred "in engine" or does it represent the time when the notification was dispatched from your end? I assume the former but wanted to double-check.

Thanks!

**Comment by revilwang** [comment]
It’s the former

**Comment by LKresta** [comment]
Splendid, thanks!
