### ISSUE TITLE
Order book update subscription params

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#38]
Hello there,

Regarding https://www.gate.io/docs/developers/futures/ws/en/#order-book-update-subscription, what is the semantics of `level` parameter? Does it refer to order book depth ~ number of bids/asks to return? Or something else? Is it different from `limit` parameter on e.g. https://www.gate.io/docs/developers/delivery/ws/en/#order-book-subscription?

Thanks,
L.

**Comment by revilwang** [comment]
Yes, they mean the same thing, number of bids/asks to return.

**Comment by LKresta** [comment]
I see, thanks!
