### ISSUE TITLE
Trades notification timestamp semantics 

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#39]
Hi there,

just to confirm - the timestamp in https://www.gate.io/docs/developers/futures/ws/en/#trades-subscription is the engine one just as with https://github.com/gateio/gatews/issues/36 and https://github.com/gateio/gatews/issues/37, right?

Thanks,
L.

**Comment by revilwang** [comment]
Use `create_time_ms` to retrieve the engine time in milliseconds

**Comment by LKresta** [comment]
Thanks & sorry for rather poor description above, thanks for reading my mind :)
L.
