### ISSUE TITLE
Fee fields in user trades notification

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#42]
Hi there,

https://www.gate.io/docs/developers/futures/ws/en/#user-trades-notification says there are `fee` and `point_fee` fields in the notification. I don't see them in notifications I receive, are these fields somehow optional (if so when are they provided) or is the documentation wrong?

Thanks,
L.

**Comment by revilwang** [comment]
Are you using gatews SDK? The two fields has been added in raw response, but the SDK is not updated. We'll update a new version later.

**Comment by LKresta** [comment]
No, I'm not using the SDK. I'm looking at output from socket connection (testnet, USDT settle).

**Comment by revilwang** [comment]
These two fields haven't been updated to testnet environment. I'll issue a server upgrade.

**Comment by LKresta** [comment]
Splendid, thanks!
