### ISSUE TITLE
How to get 'premium index' via API?

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#45]
Hello there,

I checked the documentation and samples but could not find any info on how to obtain _premium index_ values (https://www.gate.io/futures_info_new/futures/btc/BTC_USD#indexinfo, 'premium index'). Is there any way in API to retrieve this value over time/subscribe to updates/...?

Thanks,
L.

**Comment by LKresta** [comment]
I found something like `/api/v4/futures/usdt/premium_index?contract=BTC_USDT&from=1667271733&to=1667314993&interval=5m`, is it safe to use?

**Comment by revilwang** [comment]
Yes, it's safe to use. We'll also update the API details to our public documents.

**Comment by LKresta** [comment]
Great, thanks!
