### ISSUE TITLE
Balance notification timestamp semantics

### ISSUE THREAD

**Issue by LKresta** [gateio/gatews#46]
Hello there,

I have a question regarding balance notifications coming from WebSocket API (https://www.gate.io/docs/developers/futures/ws/en/#balances-notification). Does the timestamp there represent the time when the change occurred "in engine" or does it represent the time when the notification was dispatched from your end? I assume the former but wanted to double-check.

Thanks!
L.

**Comment by revilwang** [comment]
Every time or time_ms in detailed `result` response means the change occurred in engine.

**Comment by LKresta** [comment]
Ok, thanks for clarification!
