### ISSUE TITLE
local_order_book.py out of sync

### ISSUE THREAD

**Issue by ctubio** [gateio/gatews#6]
did you try to run `local_order_book.py` lately?

i see zombie levels (overlapping ask and bid price) always after the very first update.

is the orderbook of websocket v4 ready to be used in production?

thank you for your time''

**Comment by revilwang** [comment]
I'll look into this issue. Thanks for reporting.

**Comment by revilwang** [comment]
There is an issue with `spot.order_book_update` data. We're trying to figure out the root cause. You can use `spot.order_book` for full order book which can be used directly without any further handling.

**Comment by ctubio** [comment]
yea, the client source in this repo is perfect; so must be some server side issue

:koala: i cannot say since when it happens cos im new to this api since a few days ago only

meanwhile `spot.order_book` is an acceptable alternative for the first 20 levels, thank you @revilwang

**Comment by revilwang** [comment]
The issue has been confirmed from the server side. I'll let it open until the problem is fixed.

**Comment by revilwang** [comment]
The server has been patched to resolve the `spot.order_book_update` issue, and `local_order_book.py` is also updated to actively reject price overlapping.

**Comment by ctubio** [comment]
ok, hope it will be deployed to wss://api.gateio.ws/ws/v4/ soon

:koala: thank you

**Comment by revilwang** [comment]
wss://api.gateio.ws/ws/v4/ has already been updated. Besides, `spot.order_book` support 50 and 100 level subscriptions too.
