### ISSUE TITLE
[Question]: `spot.orders` websocket subscription response

### ISSUE THREAD

**Issue by Halimao** [gateio/gatews#62]
I have some questions about `Server Notification Field` of channel `spot.orders`:

1. [`finish_as`](https://www.gate.io/docs/developers/apiv4/ws/en/#server-notification-7:~:text=%C2%BB-,finish_as,-String). I didn't see a field named `finish_as` in go lib [`SpotOrderMsg`](https://github.com/gateio/gatews/blob/0a9f3ff9f49e40d7f393ad05861c462b133c9143/go/response_spot.go#L181)
2. There is a field named `Status` with a comment `// SpotOrderMsg status  - open: to be filled - closed: filled - cancelled: cancelled`. I'm not sure if this is equal to `finish_as` field.
3. For `event` field, the description of `finish` status, `order closed or cancelled`. If I receive the order event about `finish` status, how do I distinguish whether the order is closed or cancelled?
4. `avg_deal_price`. I didn't see a field named `avg_deal_price` in go lib [`SpotOrderMsg`](https://github.com/gateio/gatews/blob/0a9f3ff9f49e40d7f393ad05861c462b133c9143/go/response_spot.go#L181) too

I am looking forward to your reply

**Comment by latesun** [comment]
Hi @Halimao, thank you for bringing this to our attention. I've already submitted a [PR](https://github.com/gateio/gatews/pull/63) that addresses this issue. Please feel free to review it, and let me know if you have any further questions or suggestions.
