### ISSUE TITLE
Please report connection state of underling websocket connection

### ISSUE THREAD

**Issue by m11y** [gateio/gatews#8]

**Comment by revilwang** [comment]
This issue is unclear of the programming language used, what connection state and why do you need it

**Comment by m11y** [comment]
The websocket connection may be broken at some time，its good that gate sdk will do auto reconnect，but our business need to the market is acutally do not available when connection is broken.

Perhaps provide a method like below:

```

type ConnState string

const (
    Connected ...
    Connecting ...
    Disconnected ...
)

func (ws *WsService) GetConnState() ConnState {
	// ...
}

```

**Comment by Sinclair-Ni** [comment]
> The websocket connection may be broken at some time，its good that gate sdk will do auto reconnect，but our business need to know the market is acutally **do not available** when connection is broken.
> 
> Perhaps provide a method like below:
> 
> ```
> 
> type ConnState string
> 
> const (
>     Connected ...
>     Connecting ...
>     Disconnected ...
> )
> 
> func (ws *WsService) GetConnState() ConnState {
> 	// ...
> }
> ```

at v0.1.8 Release has added a method `GetConnection()` to get the connection. You can use this connection to solve the situation of you. And you can visit [gorilla/websocket](https://github.com/gorilla/websocket) to get more info.

**Comment by revilwang** [comment]
Close due to long time inactivity
